# Generated by Django 5.2.5 on 2025-08-10 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='publish_date',
            new_name='published_date',
        ),
    ]
